-- ============================================
-- Instalaciones Garcias - Database Schema
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- MIGRATION: Add missing columns to existing tables
-- Run this first if tables already exist
-- ============================================

-- Add status column to leads if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'leads' AND column_name = 'status'
  ) THEN
    ALTER TABLE leads ADD COLUMN status text DEFAULT 'nuevo';
    ALTER TABLE leads ADD CONSTRAINT leads_status_check 
      CHECK (status IN ('nuevo', 'contactado', 'cotizado', 'cerrado', 'perdido'));
  END IF;
END $$;

-- Add publicado column to proyectos if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'proyectos' AND column_name = 'publicado'
  ) THEN
    ALTER TABLE proyectos ADD COLUMN publicado boolean DEFAULT true;
  END IF;
END $$;

-- ============================================
-- LEADS TABLE
-- Stores contact form submissions and project inquiries
-- ============================================
CREATE TABLE IF NOT EXISTS leads (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Contact Information
  nombre text NOT NULL,
  telefono text,
  email text,
  
  -- Project Details
  tipo_servicio text,
  m2 numeric,
  urgencia text CHECK (urgencia IN ('Baja', 'Normal', 'Alta', 'Urgente')),
  mensaje text,
  
  -- Optional: Photo URLs (if user uploads images)
  fotos text[],
  
  -- Lead scoring for prioritization
  lead_score numeric DEFAULT 0,
  
  -- Status tracking
  status text DEFAULT 'nuevo' CHECK (status IN ('nuevo', 'contactado', 'cotizado', 'cerrado', 'perdido'))
);

-- Indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);

-- ============================================
-- PROYECTOS TABLE
-- Portfolio of completed projects
-- ============================================
CREATE TABLE IF NOT EXISTS proyectos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Project Information
  titulo text NOT NULL,
  descripcion text,
  location text,
  date text,
  category text,
  
  -- Images (optional - can use local frontend images instead)
  -- These can be Supabase Storage URLs or relative paths to frontend assets
  antes_url text,
  despues_url text,
  
  -- Metrics
  metros numeric,
  duracion text,
  
  -- Tags for filtering
  tags text[],
  
  -- Visibility
  publicado boolean DEFAULT true
);

-- Indexes for filtering
CREATE INDEX IF NOT EXISTS idx_proyectos_category ON proyectos(category);
CREATE INDEX IF NOT EXISTS idx_proyectos_publicado ON proyectos(publicado);

-- ============================================
-- LOG_SIMULACIONES TABLE
-- Analytics for simulator usage
-- ============================================
CREATE TABLE IF NOT EXISTS log_simulaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Simulation Parameters
  area numeric NOT NULL,
  service_type text NOT NULL,
  finish text,
  painting boolean DEFAULT false,
  
  -- Results
  estimated_days numeric,
  estimated_cost numeric,
  
  -- Optional: User tracking (if you implement sessions)
  session_id text,
  ip_address inet
);

-- Indexes for analytics queries
CREATE INDEX IF NOT EXISTS idx_log_simulaciones_created_at ON log_simulaciones(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_log_simulaciones_service_type ON log_simulaciones(service_type);

-- ============================================
-- SAMPLE DATA (Optional)
-- Uncomment to insert sample projects
-- ============================================

-- INSERT INTO proyectos (titulo, descripcion, location, date, category, metros, duracion, tags, publicado) VALUES
-- ('Centro Comercial Andares', 'Construcción de estructura principal y acabados', 'Guadalajara, JAL', '2024', 'Comercial', 5000, '8 meses', ARRAY['comercial', 'estructura'], true),
-- ('Planta Automotriz', 'Nave industrial con especificaciones técnicas avanzadas', 'Silao, GTO', '2023', 'Industrial', 12000, '12 meses', ARRAY['industrial', 'automotriz'], true),
-- ('Hospital Regional', 'Infraestructura médica de alta complejidad', 'Monterrey, NL', '2023', 'Salud', 8000, '14 meses', ARRAY['salud', 'infraestructura'], true);
